default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root  # ここを 'root' に変更
  password: pass  # mysql_secure_installation で設定したパスワード
  host: localhost
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: sample_app_development

test:
  <<: *default
  database: sample_app_test